[project]
name = "docstring-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "tree-sitter==0.21.0",
    "tree-sitter-languages==1.10.2"
]
